# Generated by Django 4.1.4 on 2022-12-30 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("auteur", "auteur"),
                            ("responsable", "responsable"),
                            ("contributeur", "contributeur"),
                        ],
                        max_length=64,
                    ),
                ),
                ("role", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=1024)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("back-end", "back-end"),
                            ("front-end", "front-end"),
                            ("IOS", "IOS"),
                            ("Android", "Android"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_project_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contribs",
                    models.ManyToManyField(
                        related_name="project_contrib_user",
                        through="globalapp.Contributors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=1024)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("BUG", "BUG"),
                            ("AMELIORATION", "Amélioration"),
                            ("TACHE", "Tâche"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVE", "Elevée"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "stats",
                    models.CharField(
                        choices=[
                            ("A faire", "A faire"),
                            ("En cours", "En cours"),
                            ("Terminé", "Terminé"),
                        ],
                        max_length=16,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "Assignee_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee_issue_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_issue_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalapp.projects",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contributors",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="globalapp.projects"
            ),
        ),
        migrations.AddField(
            model_name="contributors",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=1024)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_comment_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalapp.issues",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="contributors", unique_together={("user_id", "project_id")},
        ),
    ]
