# Generated by Django 4.1.4 on 2022-12-27 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("globalapp", "0003_alter_projects_author_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="contribs",
            field=models.ManyToManyField(
                related_name="project_contrib_user",
                through="globalapp.Contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="author_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_comment_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
